language: node_js
node_js:
- '4.4'
- '5'
- '6'
deploy:
  api_key:
    secure: o5WrXofdHiZYizk3Y0tyhYDxV1VHkr0bvGtsbSGvtKskPOYK1NpYksVlVhlvS24QYxnCg7FgElStd4qQlIoVBNE558SXjN/2/xJeEaCyGe9eViGRxBZNFfO2QlzbECRLVPQiiH9cJ5pxrpWDo40hrkDKEF1eQ+YHWZUUcjDOAFZfhCxb3S/kJ5RU3v1cZFIjJw6NU4nyVABnPbvevcbmUrg7OFzwhIwFr3xCBzdlhJ4f1L8AMJtjPBzNiZTIwqPSXPVCBBMADppyLVskiHE8TdC1IZ3y3LtyVSlbLAR0219JXj8T7bpK39Zf35Wm+vj0nVzxJWy0jB+/ycOqTK5QAYskUb4YQlyLBsHF2OrUGwAWvR7xYk2Xj/vTISQdG3oEo45LdK30jJCy0hicnIFVBblK9U77NzUf+j6wbmhkSoQqxUB27hVJY6wMOnO+lP3p2DaysKKI5ncPnGU8iYSVLv+sxwZ44ySp3aejvTQzdh8CJFmcUE74E6rTrh38wjbgvwp9DOB3LHHkl1iZgH/yhKnORqGVVWIPLKW3NamQcsfDRQnfyIPuaofYoUPidLUVYWAU8LAwS0lTJaOm2rKdSrgouZhj/J+VcLG/B4t+YovtDFy5t+HHrIX2g/c9ACpJiV0lFbyYAT5iQa9LuXFaK14CdTn0b6wLNLYU7W1HAhI=
